/**
 * PEARL Menu System Comprehensive Test Suite
 * Generated by Testing Agent - Covers all edge cases and integration points
 */

#include <gtest/gtest.h>
#include "engineering_menu.h"
#include "quadrature_encoder.h"
#include "lcd_i2c.h"

class MenuSystemTest : public ::testing::Test {
protected:
    void SetUp() override {
        // Initialize test environment
        encoder = new QuadratureEncoder(10, 11, 12);
        lcd = new LCD_I2C(0x27, 20, 4);
        menu = new EngineeringMenu(lcd, encoder);
    }

    void TearDown() override {
        delete menu;
        delete lcd;
        delete encoder;
    }

    QuadratureEncoder* encoder;
    LCD_I2C* lcd;
    EngineeringMenu* menu;
};

// HAPPY PATH TESTS
TEST_F(MenuSystemTest, ShouldActivateUserMenuNormally) {
    // Simulate triple-click activation
    for(int i = 0; i < 3; i++) {
        encoder->setButtonPressed(true);
        sleep_ms(50);
        encoder->setButtonPressed(false);
        sleep_ms(100);
    }
    
    EXPECT_TRUE(menu->isUserMenuActive());
    EXPECT_EQ(menu->getCurrentMenuLevel(), MENU_USER);
}

TEST_F(MenuSystemTest, ShouldNavigateMenuItemsCorrectly) {
    menu->activateUserMenu();
    
    // Test navigation
    encoder->setPosition(1);
    menu->update();
    EXPECT_EQ(menu->getSelectedItem(), 1);
    
    encoder->setPosition(2);
    menu->update();
    EXPECT_EQ(menu->getSelectedItem(), 2);
}

// EDGE CASES
TEST_F(MenuSystemTest, ShouldHandleMenuBoundariesCorrectly) {
    menu->activateUserMenu();
    
    // Test upper boundary
    encoder->setPosition(999);
    menu->update();
    EXPECT_LT(menu->getSelectedItem(), menu->getUserMenuItemCount());
    
    // Test lower boundary
    encoder->setPosition(-999);
    menu->update();
    EXPECT_GE(menu->getSelectedItem(), 0);
}

TEST_F(MenuSystemTest, ShouldHandleRapidInputChanges) {
    menu->activateUserMenu();
    
    // Rapid position changes
    for(int i = 0; i < 100; i++) {
        encoder->setPosition(i % 10);
        menu->update();
        sleep_us(100); // Very fast updates
    }
    
    EXPECT_TRUE(menu->isUserMenuActive()); // Should remain stable
}

// ERROR HANDLING
TEST_F(MenuSystemTest, ShouldHandleNullPointerGracefully) {
    EngineeringMenu* nullMenu = new EngineeringMenu(nullptr, nullptr);
    
    // Should not crash
    EXPECT_NO_THROW(nullMenu->update());
    EXPECT_NO_THROW(nullMenu->activateUserMenu());
    
    delete nullMenu;
}

TEST_F(MenuSystemTest, ShouldHandleMenuStackOverflow) {
    // Try to activate menu recursively
    for(int i = 0; i < 20; i++) {
        menu->activateUserMenu();
    }
    
    // Should maintain stable state
    EXPECT_TRUE(menu->isUserMenuActive());
    EXPECT_LT(menu->getMenuDepth(), 10); // Reasonable depth limit
}

// INTEGRATION TESTS
TEST_F(MenuSystemTest, ShouldIntegrateWithEncoderCorrectly) {
    // Test encoder integration
    encoder->setPosition(0);
    menu->activateUserMenu();
    
    // Physical rotation simulation
    for(int i = 0; i < 5; i++) {
        encoder->simulateRotation(1);
        menu->update();
    }
    
    EXPECT_EQ(menu->getSelectedItem(), 5);
}

// SECURITY TESTS
TEST_F(MenuSystemTest, ShouldProtectEngineeringMenuAccess) {
    // Without proper authentication
    menu->activateEngineeringMenu();
    EXPECT_FALSE(menu->isEngineeringMenuActive());
    
    // With proper bypass (for testing)
    menu->bypassEngineering();
    menu->activateEngineeringMenu();
    EXPECT_TRUE(menu->isEngineeringMenuActive());
}

// PERFORMANCE TESTS
TEST_F(MenuSystemTest, ShouldUpdateWithinPerformanceConstraints) {
    auto start = time_us_64();
    
    for(int i = 0; i < 1000; i++) {
        menu->update();
    }
    
    auto duration = time_us_64() - start;
    EXPECT_LT(duration, 100000); // Should complete in <100ms
}

// MEMORY TESTS
TEST_F(MenuSystemTest, ShouldNotLeakMemory) {
    size_t initialMemory = getFreeMemory();
    
    for(int i = 0; i < 100; i++) {
        menu->activateUserMenu();
        menu->update();
        menu->deactivate();
    }
    
    size_t finalMemory = getFreeMemory();
    EXPECT_NEAR(initialMemory, finalMemory, 1024); // Allow 1KB variance
}