/**
 * PEARL Performance Monitor Header
 * Generated by Performance Agent
 */

#ifndef PERFORMANCE_MONITOR_H
#define PERFORMANCE_MONITOR_H

#include "engineering_menu.h"
#include "quadrature_encoder.h"
#include "lcd_i2c.h"

// Performance monitoring functions
void run_performance_benchmark(EngineeringMenu* menu, QuadratureEncoder* encoder, LCD_I2C* lcd);
void run_continuous_monitoring(EngineeringMenu* menu, QuadratureEncoder* encoder, LCD_I2C* lcd);

// Performance optimization implementations
class OptimizedMenuSystem {
private:
    bool display_needs_update = false;
    bool encoder_changed = false;
    uint64_t last_encoder_position = 0;
    
public:
    // Event-driven update (Performance Agent optimization)
    void optimized_update(EngineeringMenu* menu, QuadratureEncoder* encoder);
    
    // Buffered LCD updates (Performance Agent optimization)
    void flush_display_buffer(LCD_I2C* lcd);
    
    // Adaptive encoder sampling (Performance Agent optimization)
    void adaptive_encoder_sampling(QuadratureEncoder* encoder);
};

#endif // PERFORMANCE_MONITOR_H