/**
 * PEARL Performance Monitoring and Optimization
 * Generated by Performance Agent
 */

#include "pico/stdlib.h"
#include "hardware/timer.h"
#include "engineering_menu.h"
#include "quadrature_encoder.h"
#include "lcd_i2c.h"

class PerformanceBenchmark {
private:
    EngineeringMenu* menu;
    QuadratureEncoder* encoder;
    LCD_I2C* lcd;
    
    struct BenchmarkResults {
        uint64_t menu_update_avg_us;
        uint64_t lcd_write_time_us;
        uint64_t encoder_read_avg_us;
        uint32_t free_memory_bytes;
        uint32_t cpu_utilization_percent;
    };

public:
    PerformanceBenchmark(EngineeringMenu* m, QuadratureEncoder* e, LCD_I2C* l) 
        : menu(m), encoder(e), lcd(l) {}

    BenchmarkResults runComprehensiveBenchmark() {
        BenchmarkResults results = {};
        
        printf("\n🚀 PERFORMANCE BENCHMARK STARTING...\n");
        printf("=======================================\n");
        
        // Benchmark 1: Menu Update Performance
        results.menu_update_avg_us = benchmarkMenuUpdate();
        
        // Benchmark 2: LCD Write Performance  
        results.lcd_write_time_us = benchmarkLCDWrite();
        
        // Benchmark 3: Encoder Read Performance
        results.encoder_read_avg_us = benchmarkEncoderRead();
        
        // Benchmark 4: Memory Usage
        results.free_memory_bytes = benchmarkMemoryUsage();
        
        // Benchmark 5: CPU Utilization
        results.cpu_utilization_percent = benchmarkCPUUtilization();
        
        printBenchmarkReport(results);
        return results;
    }

private:
    uint64_t benchmarkMenuUpdate() {
        printf("📊 Testing menu update performance...\n");
        
        const int iterations = 1000;
        uint64_t start = time_us_64();
        
        for(int i = 0; i < iterations; i++) {
            menu->update();
            // Simulate slight position change to test response
            if (i % 100 == 0) {
                // Trigger menu state changes periodically
            }
        }
        
        uint64_t duration = time_us_64() - start;
        uint64_t avg_per_update = duration / iterations;
        
        printf("  ✅ %d menu updates: %llu μs total (avg: %llu μs per update)\n", 
               iterations, duration, avg_per_update);
        
        return avg_per_update;
    }
    
    uint64_t benchmarkLCDWrite() {
        printf("📺 Testing LCD write performance...\n");
        
        uint64_t start = time_us_64();
        
        lcd->clear();
        lcd->set_cursor(0, 0);
        lcd->print("Performance Test");
        lcd->set_cursor(0, 1);
        lcd->print("Line 2: 1234567890");
        lcd->set_cursor(0, 2);
        lcd->print("Line 3: ABCDEFGHIJ");
        lcd->set_cursor(0, 3);
        lcd->print("Line 4: !@#$%^&*()");
        
        uint64_t duration = time_us_64() - start;
        
        printf("  ✅ Full screen write: %llu μs (%llu ms)\n", 
               duration, duration / 1000);
        
        return duration;
    }
    
    uint64_t benchmarkEncoderRead() {
        printf("🔄 Testing encoder read performance...\n");
        
        const int iterations = 10000;
        uint64_t start = time_us_64();
        
        for(int i = 0; i < iterations; i++) {
            volatile int64_t pos = encoder->get_position();
            volatile float vel = encoder->get_velocity();
            (void)pos; (void)vel; // Suppress unused warnings
        }
        
        uint64_t duration = time_us_64() - start;
        uint64_t avg_per_read = duration / iterations;
        
        printf("  ✅ %d encoder reads: %llu μs total (avg: %llu μs per read)\n",
               iterations, duration, avg_per_read);
        
        return avg_per_read;
    }
    
    uint32_t benchmarkMemoryUsage() {
        printf("💾 Testing memory usage...\n");
        
        // Simple memory estimation (Pico has 264KB RAM)
        extern char __StackLimit, __bss_end__;
        uint32_t used_memory = &__StackLimit - &__bss_end__;
        uint32_t total_memory = 264 * 1024; // 264KB total
        uint32_t free_memory = total_memory - used_memory;
        
        printf("  ✅ Estimated memory usage: %lu KB used, %lu KB free\n",
               used_memory / 1024, free_memory / 1024);
        
        return free_memory;
    }
    
    uint32_t benchmarkCPUUtilization() {
        printf("⚡ Testing CPU utilization...\n");
        
        // Simple CPU load test
        uint64_t start = time_us_64();
        uint32_t work_cycles = 0;
        
        while((time_us_64() - start) < 100000) { // 100ms test
            work_cycles++;
            // Simulate typical workload
            menu->update();
            volatile int64_t pos = encoder->get_position();
            (void)pos;
        }
        
        uint64_t actual_duration = time_us_64() - start;
        
        // Rough estimate of CPU utilization based on work accomplished
        uint32_t utilization = (work_cycles * 100) / (actual_duration / 100);
        if (utilization > 100) utilization = 100;
        
        printf("  ✅ CPU utilization estimate: %lu%% (%lu work cycles in %llu μs)\n",
               utilization, work_cycles, actual_duration);
        
        return utilization;
    }
    
    void printBenchmarkReport(const BenchmarkResults& results) {
        printf("\n📈 PERFORMANCE BENCHMARK REPORT\n");
        printf("=====================================\n");
        printf("📊 Menu Update:     %llu μs/update", results.menu_update_avg_us);
        
        // Performance assessment
        if (results.menu_update_avg_us < 10) {
            printf(" 🟢 EXCELLENT\n");
        } else if (results.menu_update_avg_us < 50) {
            printf(" 🟡 GOOD\n");
        } else {
            printf(" 🔴 NEEDS OPTIMIZATION\n");
        }
        
        printf("📺 LCD Write:       %llu μs (%llu ms)", 
               results.lcd_write_time_us, results.lcd_write_time_us / 1000);
        
        if (results.lcd_write_time_us < 50000) {
            printf(" 🟢 FAST\n");
        } else if (results.lcd_write_time_us < 100000) {
            printf(" 🟡 ACCEPTABLE\n");
        } else {
            printf(" 🔴 SLOW\n");
        }
        
        printf("🔄 Encoder Read:    %llu μs/read", results.encoder_read_avg_us);
        
        if (results.encoder_read_avg_us < 1) {
            printf(" 🟢 EXCELLENT\n");
        } else if (results.encoder_read_avg_us < 5) {
            printf(" 🟡 GOOD\n");
        } else {
            printf(" 🔴 SLOW\n");
        }
        
        printf("💾 Free Memory:     %lu KB", results.free_memory_bytes / 1024);
        
        if (results.free_memory_bytes > 100000) {
            printf(" 🟢 PLENTY\n");
        } else if (results.free_memory_bytes > 50000) {
            printf(" 🟡 ADEQUATE\n");
        } else {
            printf(" 🔴 LOW\n");
        }
        
        printf("⚡ CPU Utilization: %lu%%", results.cpu_utilization_percent);
        
        if (results.cpu_utilization_percent < 50) {
            printf(" 🟢 EFFICIENT\n");
        } else if (results.cpu_utilization_percent < 80) {
            printf(" 🟡 MODERATE\n");
        } else {
            printf(" 🔴 HIGH\n");
        }
        
        printf("=====================================\n");
        printf("🎯 Overall Status: ");
        
        int good_scores = 0;
        if (results.menu_update_avg_us < 50) good_scores++;
        if (results.lcd_write_time_us < 100000) good_scores++;
        if (results.encoder_read_avg_us < 5) good_scores++;
        if (results.free_memory_bytes > 50000) good_scores++;
        if (results.cpu_utilization_percent < 80) good_scores++;
        
        if (good_scores >= 4) {
            printf("🟢 SYSTEM PERFORMING WELL\n");
        } else if (good_scores >= 3) {
            printf("🟡 SYSTEM ACCEPTABLE\n");
        } else {
            printf("🔴 SYSTEM NEEDS OPTIMIZATION\n");
        }
        
        printf("\n");
    }
};

// Global performance monitoring functions
void run_performance_benchmark(EngineeringMenu* menu, QuadratureEncoder* encoder, LCD_I2C* lcd) {
    PerformanceBenchmark benchmark(menu, encoder, lcd);
    benchmark.runComprehensiveBenchmark();
}

void run_continuous_monitoring(EngineeringMenu* menu, QuadratureEncoder* encoder, LCD_I2C* lcd) {
    printf("🔄 Starting continuous performance monitoring...\n");
    printf("Press any key to stop monitoring.\n\n");
    
    PerformanceBenchmark benchmark(menu, encoder, lcd);
    uint32_t sample_count = 0;
    
    while(!stdio_usb_connected() || getchar_timeout_us(0) == PICO_ERROR_TIMEOUT) {
        if (sample_count % 50 == 0) { // Report every 5 seconds at 10Hz
            printf("📊 Sample #%lu - ", sample_count / 10);
            
            uint64_t start = time_us_64();
            menu->update();
            uint64_t menu_time = time_us_64() - start;
            
            printf("Menu: %llu μs, ", menu_time);
            printf("Encoder: %lld, ", encoder->get_position());
            printf("Memory: ~%lu KB free\n", 
                   (264 * 1024 - (uint32_t)(&__StackLimit - &__bss_end__)) / 1024);
        }
        
        sample_count++;
        sleep_ms(100); // 10Hz monitoring
    }
    
    printf("🛑 Performance monitoring stopped.\n");
}